spring.application.name=payguard

paypal.base-url=https://api-m.sandbox.paypal.com
paypal.client-id=${PAYPAL_CLIENT_ID:}
paypal.client-secret=${PAYPAL_CLIENT_SECRET:}

payguard.security.agent-username=${PAYGUARD_AGENT_USERNAME:}
payguard.security.agent-password=${PAYGUARD_AGENT_PASSWORD:}
payguard.security.approver-username=${PAYGUARD_APPROVER_USERNAME:}
payguard.security.approver-password=${PAYGUARD_APPROVER_PASSWORD:}
payguard.security.mandate-id=${PAYGUARD_MANDATE_ID:payguard-demo-mandate}
payguard.security.approver-mandate-id=${PAYGUARD_APPROVER_MANDATE_ID:}
payguard.security.client-mode=${PAYGUARD_SECURITY_CLIENT_MODE:machine-to-machine}
payguard.budget.mode=${PAYGUARD_BUDGET_MODE:fail-closed}
payguard.budget.daily-limit-cents=${PAYGUARD_DAILY_LIMIT_CENTS:200000}
payguard.persistence.mode=${PAYGUARD_PERSISTENCE_MODE:postgres}

spring.datasource.url=${PAYGUARD_DB_URL:jdbc:postgresql://localhost:5432/payguard}
spring.datasource.username=${PAYGUARD_DB_USERNAME:payguard}
spring.datasource.password=${PAYGUARD_DB_PASSWORD:}
spring.datasource.hikari.maximum-pool-size=${PAYGUARD_DB_POOL_SIZE:10}
spring.flyway.enabled=${PAYGUARD_FLYWAY_ENABLED:true}
spring.jpa.open-in-view=false
